### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'length') when running stage that plugin should not start on

### ISSUE THREAD

**Issue by skand888** [bealearts/serverless-mongodb-local#8]
If serverless.ts defines only one stage, such as:
```yml
  mongodb:
    stages:
      - dev
```
And start with another stage: `serverless offline start --stage test`.
The start fails with the error:
```
Error:
TypeError: Cannot read properties of null (reading 'length')
    at /home/skand/flexify/price-service/node_modules/serverless-mongodb-local/src/index.js:46:84
    at Array.some (<anonymous>)
    at ServerlessMongoDBLocal.shouldExecute (/home/skand/flexify/price-service/node_modules/serverless-mongodb-local/src/index.js:46:33)
    at ServerlessMongoDBLocal.startHandler (/home/skand/flexify/price-service/node_modules/serverless-mongodb-local/src/index.js:52:14)
    at PluginManager.runHooks (/home/skand/flexify/price-service/node_modules/serverless/lib/classes/plugin-manager.js:530:15)
    at PluginManager.invoke (/home/skand/flexify/price-service/node_modules/serverless/lib/classes/plugin-manager.js:563:20)
    at PluginManager.run (/home/skand/flexify/price-service/node_modules/serverless/lib/classes/plugin-manager.js:604:18)
    at async Serverless.run (/home/skand/flexify/price-service/node_modules/serverless/lib/serverless.js:174:5)
    at async /home/skand/flexify/price-service/node_modules/serverless/scripts/serverless.js:765:9
```
The root cause of this is `shouldExecute()` function:
```js
  shouldExecute() {
    if (this.config.stages) {
      return this.config.stages.some((stage) => this.stage.match(new RegExp(stage)).length > 0);
    }
    return true;
  }
```

`match(regexp)` returns `null` if no matches are found, not empty array.

**Comment by DavidBeale** [comment]
Thanks. Fix applied to [v1.5.1](https://github.com/bealearts/serverless-mongodb-local/tree/v1.5.1)
